project_id = "tihsuwdvmwmgzjrelepr"

[auth.email]
# Email OTP/magic link expiry in seconds. 86400 = 1 day (max).
otp_expiry = 86400

[functions.send-invitation]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false
